language: node_js
node_js:
 - "node"
after_success:
 - git config --global user.name "juanmndz"
 - git config --global user.email "juanmndz19@gmail.com"
 - git remote rm origin
 - git remote add origin https://vijayabharathib:${GH_TOKEN}@github.com/pineboat/react-continuous-deployment.git
 - npm run deploy